### ISSUE TITLE
How to deploy these smart contracts on Testnet?

### ISSUE THREAD

**Issue by nzee** [ethereum-boilerplate/web3-social-network-boilerplate#3]
`truffle deploy` command only compiles and deploys MetaCoin but not the decentradit.sol. Can someone suggest the best way to deploy on testnet and get contact addresses to be added to the Moralis watch and sync events.

**Comment by tippi-fifestarr** [comment]
If you want, you can just deploy the contract by pasting it into Remix and then copy/pasting the ABI and address into the appropriate spots in our friend MoralisDappProvider.js.  

For the truffle route:
1. Delete Metacoin from the contracts and replace with decentradit.sol
2. Try checking your deploy script to deploy decentradit not MetaCoin... 
3. Are your .env correct?
4. still got to paste that info into MDP.js

**Comment by Daniel-Itzul** [comment]
I would really want to give a shoutout to @tippi-fifestarr you have been great help for the community regarding this project with your questions and collaboration helping other builders.

As with regard to the specific question. I have a mea culpa. The Truffle folder was inherited from the original Ethereum boilerplate repo which this project inherits from. 
In the video it is mentioned that the deployment of the contracts is not included in the code. This is because people has very strong preferences on what Smart Contract development platform to use. Some people like hardhat, some truffle, I like brownie for example, for quick deployment of an already development contract a lot of people would use Remix. 

To avoid pushing people to any specific stack only the source code of the contract was intended to be provided. However, since I forgot to delete the inherited truffle project, someone familiar would truffle could change the contract in the truffle project and modify the truffle scripts to adapt to decentradit, as described by @tippi-fifestarr. 

Since this was not the intention and the project was to be framework neutral I deleted the truffle project, this would eliminate any confusion as to the need of changing or implementing a truffle project.
